"""modify news event table

Revision ID: ef22085699ce
Revises: 2ed36e234faf
Create Date: 2025-12-14 15:32:39.922158

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef22085699ce"
down_revision: Union[str, Sequence[str], None] = "2ed36e234faf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_events", sa.Column("ts_release_ms", sa.Integer(), nullable=True)
    )  # nullable set to true so populate_tables.py can be run later
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_events", "ts_release_ms")
    # ### end Alembic commands ###
