name: Run Pytest on Pull Requests

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run pytest with coverage
        working-directory: backend
        run: |
          pytest --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing
