name: Run Pytest on Pull Requests

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,test]

      - name: Create .env file for CI
        working-directory: backend
        run: |
          echo "DATABASE_URL=postgresql://user:password@postgres:5432/testdb" > .env

      - name: Run pytest with coverage
        working-directory: backend
        env:
          DATABASE_URL: postgresql://user:password@postgres:5432/testdb
        run: |
          pytest --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing
